/*
 * RautorViewerAboutBox.java
 */

package rautorviewer;

import org.jdesktop.application.Action;
import javax.swing.KeyStroke;
import java.awt.event.*;
import java.awt.Color;
import javax.swing.JComponent;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;

public class RautorViewerTextBox extends javax.swing.JDialog {

    public RautorViewerTextBox(java.awt.Frame parent,String Contents,int start,int end) {
        super(parent);
        initComponents();

        jTextArea1.setText(Contents);
        jTextArea1.setCaretPosition(start);
        Highlighter h=jTextArea1.getHighlighter();

        if ( ( start != 0) && ( end != 0 ) ) {
            HighLight(Contents,h,start,end);
        }

        KeyStroke stroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        rootPane.registerKeyboardAction(actionListener, stroke, JComponent.WHEN_IN_FOCUSED_WINDOW);
    }

    //   ***********************************************************

    void HighLight(String Contents,Highlighter h,int start,int end){
        h.removeAllHighlights();        
        try {               
                h.addHighlight(start, end,new MyHighlightPainter(Color.pink));
        } catch (Exception ignore) {}
    }


   //   ***********************************************************
    @Action public void closeAboutBox() {
        dispose();
    }


    //   ***********************************************************
 ActionListener actionListener = new ActionListener() {
  public void actionPerformed(ActionEvent actionEvent) {
     dispose();
  }
};

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextPane1.setName("jTextPane1"); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(rautorviewer.RautorViewerApp.class).getContext().getResourceMap(RautorViewerTextBox.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setModal(true);
        setName("aboutBox"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jTextArea1.setForeground(resourceMap.getColor("jTextArea1.foreground")); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
    
}

class MyHighlightPainter extends DefaultHighlighter.DefaultHighlightPainter {
   public MyHighlightPainter(Color color) {
      super(color);
   }
}
