; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D5B5C256-BBF6-4AE8-AA67-AD657EA1815E}
AppName=Rautor Commercial
AppVerName=Rautor_com 2.3
AppPublisher=www.unix.gr
AppPublisherURL=http://www.unix.gr/rautor
AppSupportURL=http://www.unix.gr/rautor
AppUpdatesURL=http://www.unix.gr/rautor
DefaultDirName={pf}\Rautor Commercial
DefaultGroupName=Rautor Commercial
AllowNoIcons=yes
OutputDir=C:\Rautor_Com
OutputBaseFilename=Rautor_com_setup
SetupIconFile=C:\Rautor\bull-old.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: english; MessagesFile: compiler:Default.isl

[Tasks]
Name: desktopicon; Description: {cm:CreateDesktopIcon}; GroupDescription: {cm:AdditionalIcons}; Flags: unchecked
Name: quicklaunchicon; Description: {cm:CreateQuickLaunchIcon}; GroupDescription: {cm:AdditionalIcons}; Flags: unchecked

[Files]
Source: C:\Rautor_Com\Rautor_com.exe; DestDir: {app}; Flags: ignoreversion
Source: C:\Rautor_Com\Rau_web.exe; DestDir: {app}; Flags: ignoreversion
Source: C:\Rautor_Com\rrs.exe; DestDir: {app}; Flags: ignoreversion
Source: C:\Rautor_Com\UnsetProxy.exe; DestDir: {app}; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: {group}\Rautor Commercial; Filename: {app}\Rautor_com.exe
Name: {group}\{cm:UninstallProgram,Rautor Commercial}; Filename: {uninstallexe}

[Run]
Filename: {app}\Rautor_com.exe; Description: {cm:LaunchProgram,Rautor Commercial}; Flags: nowait postinstall skipifsilent

[Registry]
Root: HKLM; Subkey: SOFTWARE\Microsoft\Windows\CurrentVersion\Run; ValueType: string; ValueName: Rautor_com; ValueData: {app}\Rautor_com.exe; Flags: uninsdeletevalue
Root: HKLM; Subkey: SOFTWARE\Microsoft\Windows\CurrentVersion\Run; ValueType: string; ValueName: RautorWeb; ValueData: {app}\Rau_web.exe; Flags: uninsdeletevalue
Root: HKLM; Subkey: SOFTWARE\Rautor; Flags: uninsdeletekey
Root: HKLM; Subkey: SOFTWARE\Wow6432Node\Rautor; Flags: uninsdeletekey
[UninstallDelete]
Name: {app}\Rau_web.exe; Type: filesandordirs
Name: {app}\Rautor_com.exe; Type: filesandordirs
Name: {app}\rrs.exe; Type: filesandordirs
Name: {app}\UnsetProxy.exe; Type: filesandordirs
Name: {app}; Type: dirifempty
