


all:  coliau.exe

PP=c:\\perl\\site\\bin\\pp.bat

coliau.exe: coliau.pl rau_html.pl firewallopen.pl Keymap.pl firewallopen.pl dot_ico.pl bull_lined.pl
        pp  --icon=camera.ico    --verbose=3  --gui -o coliau.exe coliau.pl
